stages:
- build
- integration
- test
- deploy

build-lib:
  image: node
  stage: build
  script:
  - npm ci
  - npm run test
  artifacts:
    expire_in: 1 week
    paths:
    - dist/w11k/ngx-select

#build-demo:
#  image: node
#  dependencies:
#  - build-lib
#  stage: integration
#  script:
#  - npm ci
#  - npm run build
#  artifacts:
#    expire_in: 1 week
#    paths:
#    - dist/ngx-select-demo

#publish-demo:
#  image: node
#  stage: deploy
#  dependencies:
#  - build-lib
#  - build-demo
#  only:
#  - master
#  - web
#  script:
#  - git push https://${GITHUB_TOKEN}@github.com/w11k/angular-sticky-things master
#  - npx ngh --dir=dist/angular-sticky-things-demo --message=\"updates demo\" --repo=https://${GITHUB_TOKEN}@github.com/w11k/angular-sticky-things

publish:
  image: node:alpine
  stage: deploy
  dependencies:
  - build-lib
  only:
  - tags
  script:
  - cd dist/w11k/ngx-select
  - cp ../../../README.md .
  - cp ../../../LICENSE .
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
  - npm publish --access=public

